In [17]:
import pandas as pd
import sqlite3
df=pd.read_csv("/content/Sample - Superstore.csv",encoding="latin1")
print("Dataset Shape:",df.shape)
df.head()

Dataset Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [18]:
conn = sqlite3.connect("superstore.db")
df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)
print("Table Created Successfully")

Table Created Successfully

In [19]:
query = """
PRAGMA table_info(superstore);
"""
pd.read_sql(query, conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

In [20]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [21]:
query = """
SELECT COUNT(*) AS total_rows
FROM superstore;
"""

pd.read_sql(query, conn)

   total_rows
0        9994

In [22]:
query = """
SELECT *
FROM superstore
WHERE Region='South';
"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
4,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,9972,CA-2015-103772,6/28/2015,7/2/2015,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,...,30080,South,OFF-AR-10000538,Office Supplies,Art,"Boston Model 1800 Electric Pencil Sharpener, Gray",140.7500,5,0.00,42.2250
1616,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
1617,9988,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964
1618,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
1619,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028

In [23]:
query = """
SELECT *
FROM superstore
WHERE Category='Office Supplies';
"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
1,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
2,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
3,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
4,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6021,9983,US-2016-157728,9/22/2016,9/28/2016,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.560,7,0.0,16.7132
6022,9985,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
6023,9986,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240
6024,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
6025,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [24]:
query = """
SELECT *
FROM superstore
WHERE Sales > 2367;
"""
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
1,166,CA-2014-139892,9/8/2014,9/12/2014,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,...,78207,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920
2,252,CA-2016-145625,9/11/2016,9/17/2016,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,...,92037,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.370,13,0.0,636.0003
3,263,US-2014-106992,9/19/2014,9/21/2014,Second Class,SB-20290,Sean Braxton,Corporate,United States,Houston,...,77036,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,3059.982,3,0.4,-509.9970
4,264,US-2014-106992,9/19/2014,9/21/2014,Second Class,SB-20290,Sean Braxton,Corporate,United States,Houston,...,77036,Central,TEC-MA-10003353,Technology,Machines,Xerox WorkCentre 6505DN Laser Multifunction Pr...,2519.958,7,0.4,-251.9958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,9661,CA-2016-160717,6/6/2016,6/11/2016,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Santa Barbara,...,93101,West,TEC-PH-10001459,Technology,Phones,Samsung Galaxy Mega 6.3,3023.928,9,0.2,226.7946
107,9742,CA-2015-117086,11/8/2015,11/12/2015,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,5408,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900,5,0.0,1013.1270
108,9858,CA-2015-164301,3/26/2015,3/30/2015,Standard Class,EB-13840,Ellis Ballard,Corporate,United States,Seattle,...,98103,West,FUR-TA-10001889,Furniture,Tables,Bush Advantage Collection Racetrack Conference...,3393.680,8,0.0,610.8624
109,9930,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
110,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

In [25]:
query = """
SELECT
Region,
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""
pd.read_sql(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

In [26]:
query = """
SELECT
Category,
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""
pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [27]:
query = """
SELECT
Category,
AVG(Sales) AS Average_Sales,
SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY Category;
"""
pd.read_sql(query, conn)

          Category  Average_Sales  Total_Quantity
0        Furniture     349.834887            8028
1  Office Supplies     119.324101           22906
2       Technology     452.709276            6939

In [28]:
query = """
SELECT
[Product Name],
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 15;
"""
pd.read_sql(query, conn)

                                         Product Name  Total_Sales
0               Canon imageCLASS 2200 Advanced Copier   61599.8240
1   Fellowes PB500 Electric Punch Plastic Comb Bin...   27453.3840
2   Cisco TelePresence System EX90 Videoconferenci...   22638.4800
3        HON 5400 Series Task Chairs for Big and Tall   21870.5760
4          GBC DocuBind TL300 Electric Binding System   19823.4790
5    GBC Ibimaster 500 Manual ProClick Binding System   19024.5000
6                Hewlett Packard LaserJet 3310 Copier   18839.6860
7   HP Designjet T520 Inkjet Large Format Printer ...   18374.8950
8           GBC DocuBind P400 Electric Binding System   17965.0680
9         High Speed Automatic Electric Letter Opener   17030.3120
10          Lexmark MX611dhe Monochrome Laser Printer   16829.9010
11  Martin Yale Chadless Opener Electric Letter Op...   16656.2000
12               Ibico EPK-21 Electric Binding System   15875.9160
13  Riverside Palais Royal Lawyers Bookcase, Royal...   15610.9656
14   3D Systems Cube Printer, 2nd Generation, Magenta   14299.8900

In [30]:
query = """
SELECT
[Customer Name],
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [31]:
query = """
SELECT
substr([Order Date],7,4) || '-' ||
substr([Order Date],1,2) AS Month,

SUM(Sales) AS Revenue
FROM superstore
GROUP BY Month
ORDER BY Month;
"""
pd.read_sql(query, conn)

      Month     Revenue
0    014-1/   9378.0490
1    014-10   3515.0070
2    014-11  21431.4170
3    014-12  16132.8500
4    014-2/   3082.4580
..      ...         ...
91  2016-11  60942.4890
92  2016-12  63025.0120
93  2017-10  53817.5522
94  2017-11  79834.1920
95  2017-12  47009.7178

[96 rows x 2 columns]

In [32]:
query = """
SELECT
[Order ID],
COUNT(*) AS duplicate_count

FROM superstore

GROUP BY [Order ID]

HAVING COUNT(*) > 1;
"""

pd.read_sql(query, conn)

            Order ID  duplicate_count
0     CA-2014-100090                2
1     CA-2014-100363                2
2     CA-2014-100678                4
3     CA-2014-100706                2
4     CA-2014-100762                4
...              ...              ...
2466  US-2017-168116                2
2467  US-2017-169320                2
2468  US-2017-169488                2
2469  US-2017-169502                2
2470  US-2017-169551                6

[2471 rows x 2 columns]

In [33]:
query = """
SELECT COUNT(*) AS Missing_Customers
FROM superstore
WHERE [Customer Name] IS NULL;
"""
pd.read_sql(query, conn)

   Missing_Customers
0                  0

In [34]:
query = """
SELECT COUNT(*) AS Missing_Products
FROM superstore
WHERE [Product Name] IS NULL;
"""

pd.read_sql(query, conn)

   Missing_Products
0                 0

# Week 2 Insights

1. Technology category generated significant revenue compared to other categories.

2. Sales performance varied across different regions.

3. A small number of customers contributed a large portion of overall sales.

4. Monthly sales trends showed fluctuations over time.

5. Top-selling products contributed substantially to total revenue.

6. Duplicate Order IDs exist because a single order may contain multiple products.

7. Data quality checks showed minimal missing values.